FROM datamechanics/spark:3.1-latest
ENV PYSPARK_MAJOR_PYTHON_VERSION=3

RUN pip install --upgrade pip --user \
          && pip install scikit-learn \
         && pip install pandas \
         && pip install pyspark

COPY TrainingDataset.csv ~/MyDockerImages/
COPY ValidationDataset.csv ~/MyDockerImages/ 
COPY predict.py ~/MyDockerImages/
COPY training.py ~/MyDockerImages/

CMD python training.py
ENTRYPOINT ["python","predict.py"]
