 FROM datamechanics/spark:3.1-latest

ENV PYSPARK_MAJOR_PYTHON_VERSION=3

RUN pip3 install --upgrade pip --user \
      
    && pip install pyspark \
    && pip install scikit-learn \

    && mkdir ~/MyDockerImages \
    && pip install pandas

 
 

 
COPY predict.py ~/MyDockerImages/
COPY training.py ~/MyDockerImages/
COPY TrainingDataset.csv ~/MyDockerImages/



WORKDIR ~/MyDockerImages/

CMD python training.py
RUN cd ~/MyDockerImages
ENTRYPOINT ["python","predict.py"]
